version: "3"
services:
  php:
    build: .docker/php
    container_name: "php"
    image: server-apache
    volumes:
      - .docker/apache/ssl/mycert.crt:/etc/ssl/certs/mycert.crt
      - .docker/apache/ssl/mycert.key:/etc/ssl/private/mycert.key
      - .docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - .:/var/www/html
    command: >
      bash -c "a2enmod rewrite
      && apache2-foreground && a2enmod ssl && a2enmod socache_shmcb"
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      mynetwork:
        # ipv4_address: 172.20.0.2

  mysql:
    image: mysql:5.7.26
    container_name: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      -  db_data:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - ./.docker/config.env
    restart: always
    networks:
     mynetwork:
        # ipv4_address: 172.20.0.3

  phpmyadmin:
    container_name: "phpmyadmin"
    image: phpmyadmin/phpmyadmin:5.1.1
    restart: always
    depends_on:
      - mysql
    ports:
      - "3000:80"
    networks:
      mynetwork:
    environment:
      PMA_HOST: mysql
      PMA_PMADB: phpmyadmin
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 1G
      MAX_LIFE_TIME: 100000
      MAX_EXECUTION_TIME: 100000


volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: 172.20.0.0/24